import { CategoryListResponse } from "./product.types";

const MOCK_IMAGE_URL = "https://i.imgur.com/3REtmaR.jpeg";
export const HOME_CATEGORIES: CategoryListResponse[] = [
  {
    id: "cat_doll",
    name: "Outfit & Doll",
    slug: "outfit-doll",
    description: "Doll, outfit và phụ kiện dễ thương",
    images: ["/images/categories/doll.jpg"],
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    products: [
      {
        id: "prd_001",
        sku: "DOLL-SEONGHYEON",
        name: "[SEONGHYEON] Yom Miomiao",
        slug: "seonghyeon-yom-miomiao",
        category_id: "cat_doll",
        product_type: "preorder",
        price: 280000,
        currency: "VND",
        price_note: null,
        shipping_note: "Hàng preorder, về sau 5–15 ngày",
        stock: 0,
        seller_name: "Miomiao",
        size_description: "15cm",
        package_description: "Full set",
        preorder_description: "Pre-order đợt 1",
        images: [MOCK_IMAGE_URL],
        view_count: 120,
        preorder: {
          start_date: "2024-03-01",
          end_date: "2024-03-10",
        },
        created_at: "2024-02-01",
        updated_at: "2024-02-01",
      },
      {
        id: "prd_002",
        sku: "DOLL-NIKI",
        name: "[NI-KI] Doll Outfit",
        slug: "niki-doll-outfit",
        category_id: "cat_doll",
        product_type: "in_stock",
        price: 420000,
        currency: "VND",
        price_note: null,
        shipping_note: "Có sẵn",
        stock: 5,
        seller_name: null,
        size_description: "20cm",
        package_description: null,
        preorder_description: null,
        images: [MOCK_IMAGE_URL],
        view_count: 90,
        preorder: null,
        created_at: "2024-02-02",
        updated_at: "2024-02-02",
      },
    ],
  },

  {
    id: "cat_merch",
    name: "Merch",
    slug: "merch",
    description: "Sticker, badge, goods chính hãng",
    images: ["/images/categories/merch.jpg"],
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    products: [
      {
        id: "prd_010",
        sku: "CORTIS-STICKER",
        name: "[CORTIS] Sticker trong suốt",
        slug: "cortis-sticker-trong-suot",
        category_id: "cat_merch",
        product_type: "in_stock",
        price: 44000,
        currency: "VND",
        price_note: null,
        shipping_note: "Có sẵn",
        stock: 20,
        seller_name: "Cortis",
        size_description: null,
        package_description: "Set 5 sticker",
        preorder_description: null,
        images: [MOCK_IMAGE_URL],
        view_count: 300,
        preorder: null,
        created_at: "2024-02-05",
        updated_at: "2024-02-05",
      },
    ],
  },

  {
    id: "cat_other",
    name: "Khác",
    slug: "other",
    description: "Order theo yêu cầu, quà tặng handmade",
    images: ["/images/categories/other.jpg"],
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    products: [
      {
        id: "prd_020",
        sku: "CUSTOM-ORDER",
        name: "Order theo yêu cầu",
        slug: "order-theo-yeu-cau",
        category_id: "cat_other",
        product_type: "preorder",
        price: 1000,
        currency: "VND",
        price_note: "Giá từ",
        shipping_note: "Tuỳ sản phẩm",
        stock: 0,
        seller_name: null,
        size_description: null,
        package_description: null,
        preorder_description: "Inbox để báo giá",
        images: [MOCK_IMAGE_URL],
        view_count: 999,
        preorder: null,
        created_at: "2024-02-10",
        updated_at: "2024-02-10",
      },
    ],
  },
];