/**
 * Mock products for sticker shop (20 items).
 * Each product links to a category by slug and includes variants.
 * Used by seed-mock.ts to populate the database.
 */

export interface MockVariant {
  name: string;
  description: string | null;
  price: number | null;
  stock: number | null;
  images: string[];
}

export interface MockProduct {
  name: string;
  slug: string;
  categorySlug: string;
  productType: "in_stock" | "preorder";
  price: number | null;
  stock: number | null;
  currency?: string;
  priceNote: string | null;
  shippingNote: string | null;
  viewCount?: number;
  sellerName: string;
  sizeDescription: string | null;
  packageDescription: string | null;
  preorderDescription: string | null;
  images: string[];
  variants: MockVariant[];
}

export const mockProducts: MockProduct[] = [
  {
    name: "Kawaii Cat Sticker Sheet",
    slug: "kawaii-cat-sticker-sheet",
    categorySlug: "cute-animals",
    productType: "in_stock",
    price: 45000,
    stock: 120,
    currency: "VND",
    priceNote: null,
    shippingNote: "Free ship đơn từ 100k",
    viewCount: 234,
    sellerName: "StickerLand",
    sizeDescription: "Sheet 15x10cm, ~20 stickers",
    packageDescription: "1 sheet có bóng, bảo quản khô ráo",
    preorderDescription: null,
    images: [],
    variants: [
      { name: "Sheet 1", description: "Bản in thường", price: 45000, stock: 60, images: [] },
      { name: "Sheet 2", description: "Bản hologram", price: 55000, stock: 60, images: [] },
    ],
  },
  {
    name: "Bunny Pastel Sticker Pack",
    slug: "bunny-pastel-sticker-pack",
    categorySlug: "cute-animals",
    productType: "in_stock",
    price: 35000,
    stock: 85,
    currency: "VND",
    priceNote: "Giá đã bao gồm bìa",
    shippingNote: "Giao 2-3 ngày",
    viewCount: 189,
    sellerName: "Pastel World",
    sizeDescription: "Mỗi sticker ~3-5cm",
    packageDescription: "1 túi 12 stickers",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Panda Roll Stickers",
    slug: "panda-roll-stickers",
    categorySlug: "cute-animals",
    productType: "in_stock",
    price: null,
    stock: null,
    currency: "VND",
    priceNote: "Xem giá từng size bên dưới",
    shippingNote: null,
    viewCount: 412,
    sellerName: "Cute Panda Shop",
    sizeDescription: "Roll 5m, nhiều size",
    packageDescription: "1 cuộn có hộp",
    preorderDescription: null,
    images: [],
    variants: [
      { name: "Roll 2cm", description: "Kích thước 2cm", price: 65000, stock: 30, images: [] },
      { name: "Roll 3cm", description: "Kích thước 3cm", price: 85000, stock: 25, images: [] },
      { name: "Roll 5cm", description: "Kích thước 5cm", price: 120000, stock: 15, images: [] },
    ],
  },
  {
    name: "Doggo Meme Stickers",
    slug: "doggo-meme-stickers",
    categorySlug: "cute-animals",
    productType: "in_stock",
    price: 28000,
    stock: 200,
    currency: "VND",
    priceNote: null,
    shippingNote: "Chưa bao gồm ship",
    viewCount: 567,
    sellerName: "Meme Sticker Co",
    sizeDescription: "~4cm round",
    packageDescription: "6 stickers/ set",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Hamster Study Time",
    slug: "hamster-study-time",
    categorySlug: "cute-animals",
    productType: "preorder",
    price: 52000,
    stock: 0,
    currency: "VND",
    priceNote: "Preorder ưu đãi",
    shippingNote: "Giao sau 10-14 ngày",
    viewCount: 98,
    sellerName: "Study Buddy",
    sizeDescription: "Sheet A6",
    packageDescription: "1 sheet + 1 bookmark",
    preorderDescription: "10-14 ngày",
    images: [],
    variants: [],
  },
  {
    name: "Sushi & Ramen Sticker Set",
    slug: "sushi-ramen-sticker-set",
    categorySlug: "kawaii-food-drinks",
    productType: "in_stock",
    price: 42000,
    stock: 75,
    currency: "VND",
    priceNote: null,
    shippingNote: "Free ship từ 80k",
    viewCount: 312,
    sellerName: "Foodie Stickers",
    sizeDescription: "Mix size 2-6cm",
    packageDescription: "15 stickers/ set",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Boba Tea Character Stickers",
    slug: "boba-tea-character-stickers",
    categorySlug: "kawaii-food-drinks",
    productType: "in_stock",
    price: 38000,
    stock: 90,
    currency: "VND",
    priceNote: null,
    shippingNote: null,
    viewCount: 445,
    sellerName: "Boba Lovers",
    sizeDescription: "~3cm",
    packageDescription: "10 stickers",
    preorderDescription: null,
    images: [],
    variants: [
      { name: "Set A", description: "Ly trà sữa", price: 38000, stock: 45, images: [] },
      { name: "Set B", description: "Ly trà đào", price: 38000, stock: 45, images: [] },
    ],
  },
  {
    name: "Croissant & Coffee Mini Sheet",
    slug: "croissant-coffee-mini-sheet",
    categorySlug: "kawaii-food-drinks",
    productType: "in_stock",
    price: 25000,
    stock: 150,
    currency: "VND",
    priceNote: "Mini sheet A7",
    shippingNote: "Giao nhanh nội thành",
    viewCount: 178,
    sellerName: "Cafe Sticker",
    sizeDescription: "A7, ~8 stickers",
    packageDescription: "1 sheet",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Cake Slice Sticker Pack",
    slug: "cake-slice-sticker-pack",
    categorySlug: "kawaii-food-drinks",
    productType: "in_stock",
    price: 33000,
    stock: 62,
    currency: "VND",
    priceNote: null,
    shippingNote: null,
    viewCount: 221,
    sellerName: "Sweet Stickers",
    sizeDescription: "3-4cm",
    packageDescription: "12 stickers",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Fruit Friends Preorder",
    slug: "fruit-friends-preorder",
    categorySlug: "kawaii-food-drinks",
    productType: "preorder",
    price: 48000,
    stock: 0,
    currency: "VND",
    priceNote: "Preorder đợt 2",
    shippingNote: "Giao dự kiến 15/03",
    viewCount: 134,
    sellerName: "Fruit Studio",
    sizeDescription: "Sheet 10x15cm",
    packageDescription: "1 sheet 20 designs",
    preorderDescription: "7-10 ngày",
    images: [],
    variants: [],
  },
  {
    name: "Anime Girl Chibi Stickers",
    slug: "anime-girl-chibi-stickers",
    categorySlug: "anime-characters",
    productType: "in_stock",
    price: 55000,
    stock: 45,
    currency: "VND",
    priceNote: "Bản giới hạn",
    shippingNote: "Bọc cẩn thận",
    viewCount: 892,
    sellerName: "Anime Sticker Store",
    sizeDescription: "4-5cm",
    packageDescription: "1 sheet 10 designs",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Genshin Impact Mini Stickers",
    slug: "genshin-impact-mini-stickers",
    categorySlug: "anime-characters",
    productType: "in_stock",
    price: 40000,
    stock: 78,
    currency: "VND",
    priceNote: "Fan-made, không chính thức",
    shippingNote: null,
    viewCount: 1203,
    sellerName: "Teyvat Stickers",
    sizeDescription: "2-3cm",
    packageDescription: "15 stickers random",
    preorderDescription: null,
    images: [],
    variants: [{ name: "Random set", description: "15 random nhân vật", price: 40000, stock: 78, images: [] }],
  },
  {
    name: "Demon Slayer Hashira Sheet",
    slug: "demon-slayer-hashira-sheet",
    categorySlug: "anime-characters",
    productType: "in_stock",
    price: 62000,
    stock: 32,
    currency: "VND",
    priceNote: null,
    shippingNote: "Có poster A5 tặng kèm",
    viewCount: 654,
    sellerName: "Anime Sticker Store",
    sizeDescription: "Sheet A5",
    packageDescription: "1 sheet + 1 poster",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "One Piece Wanted Poster Style",
    slug: "one-piece-wanted-poster-style",
    categorySlug: "anime-characters",
    productType: "in_stock",
    price: 35000,
    stock: 88,
    currency: "VND",
    priceNote: null,
    shippingNote: null,
    viewCount: 445,
    sellerName: "Grand Line Shop",
    sizeDescription: "4x6cm",
    packageDescription: "8 stickers",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Studio Ghibli Sticker Collection",
    slug: "studio-ghibli-sticker-collection",
    categorySlug: "anime-characters",
    productType: "preorder",
    price: 78000,
    stock: 0,
    currency: "VND",
    priceNote: "Preorder đợt 1",
    shippingNote: "Giao 20 ngày",
    viewCount: 1567,
    sellerName: "Ghibli Fan Art",
    sizeDescription: "Mix size",
    packageDescription: "25 stickers + 1 postcard",
    preorderDescription: "15-20 ngày",
    images: [],
    variants: [],
  },
  {
    name: "Reaction Faces Sticker Pack",
    slug: "reaction-faces-sticker-pack",
    categorySlug: "emoji-expressions",
    productType: "in_stock",
    price: 22000,
    stock: 250,
    currency: "VND",
    priceNote: null,
    shippingNote: "Best seller",
    viewCount: 2103,
    sellerName: "Meme Sticker Co",
    sizeDescription: "~3cm round",
    packageDescription: "20 faces",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Crying Cat & Dog Expressions",
    slug: "crying-cat-dog-expressions",
    categorySlug: "emoji-expressions",
    productType: "in_stock",
    price: 30000,
    stock: 110,
    currency: "VND",
    priceNote: null,
    shippingNote: null,
    viewCount: 567,
    sellerName: "StickerLand",
    sizeDescription: "4cm",
    packageDescription: "10 stickers",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Minimal Line Art Stickers",
    slug: "minimal-line-art-stickers",
    categorySlug: "decorative-aesthetic",
    productType: "in_stock",
    price: 45000,
    stock: 68,
    currency: "VND",
    priceNote: "Chất liệu vinyl",
    shippingNote: "Free ship từ 100k",
    viewCount: 389,
    sellerName: "Aesthetic Co",
    sizeDescription: "2-4cm",
    packageDescription: "1 sheet 16 designs",
    preorderDescription: null,
    images: [],
    variants: [],
  },
  {
    name: "Floral & Botanical Sheet",
    slug: "floral-botanical-sheet",
    categorySlug: "decorative-aesthetic",
    productType: "in_stock",
    price: 52000,
    stock: 42,
    currency: "VND",
    priceNote: null,
    shippingNote: null,
    viewCount: 278,
    sellerName: "Botanical Stickers",
    sizeDescription: "A6 sheet",
    packageDescription: "1 sheet có bóng",
    preorderDescription: null,
    images: [],
    variants: [
      { name: "Bản thường", description: "In matte", price: 52000, stock: 25, images: [] },
      { name: "Bản bóng", description: "In bóng", price: 58000, stock: 17, images: [] },
    ],
  },
  {
    name: "Retro 90s Aesthetic Pack",
    slug: "retro-90s-aesthetic-pack",
    categorySlug: "decorative-aesthetic",
    productType: "in_stock",
    price: 48000,
    stock: 55,
    currency: "VND",
    priceNote: "Limited design",
    shippingNote: "Giao 2-4 ngày",
    viewCount: 412,
    sellerName: "Retro Sticker",
    sizeDescription: "Mix 3-5cm",
    packageDescription: "18 stickers",
    preorderDescription: null,
    images: [],
    variants: [],
  },
];
